### ISSUE TITLE
"Change per (%)" field does not accept decimal values

### ISSUE THREAD

**Issue by oolong-osrs** [JammaBro/ShopCalc#3]
Hi, I attempted to use this plugin to calculate prices for nature runes from the Yanille rune shop. The appropriate change rate is 0.1%, but the calculator seems to only accepts integers in this field.

Could you please add support for decimal values to this field? Looks like you can just remove this line: https://github.com/JammaBro/Shop-Calculator/blob/a4e496f5573bc60966c70d84fb2852349bb365bb/src/main/java/com/shopcalculator/ui/ShopCalculatorPanel.java#L30C1-L30C6

**Comment by JamiMaki** [comment]
Changed the input field filtering from integer only to numeric to allow decimal values. Pull request is set for the update on Plugin-Hub so the update should go live in matter of days.
